language: java
jdk:
- oraclejdk12
script: mvn verify
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: dro873PHOc/DWPwmVwVgKNGBFIV28xloT3t5qir5hhxniERC1MZP54PWWup9rSfSP1B71XUp/iYTm/+Ib2fIUU4L7T7vAemwqmziAePl0IOiLYoB2D9UAenxrk/aA+Xat+qGa6ARy9otibYhhHf5B1xsceeu+YEmjw1uGN5cB0rvdqFyuOH+XbbbzANB53ytZ4cFJYPEeW3G1GVFFfdDmYtLmlAGrmn98JbAMBR/mRTKdWtLt2PQcIdGhdbQtwyIpHEqA+cWq2PkXOkaZ+ogAZT0vQCRBccmFpNeCc+dC9L/sdcy+I3pM3QCUvAHpobem643el2tM5M1JLZZjS4UDBEgq9HKybD52ocVthaVoWK5cOSiz17SEta+eUqeMTBCeQnjIXA0KyVstymyDp88TmYxRzrOjkVSxfSagEqCIl4NDDO9MnLElrEOHpFCe318vEkfO/2j2P7ymoiRDXTaNgge5sqwHbU+dnx1cavIy34mCkyasSxifjxf2iSqD0maNSMTO14yJvfy23R+tyxeydHU96vHAn7dfsWJqc87bxXHS/Efjw3Qkzk1Ippan6xLctqNFUZE/m2DNn28R/dXT+aw3WfqLNvTLfCRpMcuGMTS59J5XaixyaxntLQVKdVzE4+KcNefwAvv08XdGw7D9IZqy88gm6P8mMo+Sq0b2EQ=
  app: bali-compiler-server
  on:
    branch: master
