language: java
jdk:
- oraclejdk12
script: mvn verify
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: dP1gyTcHU5tnaIZ132mbtbFVVdf7zaaWMEGRvUGYo/qPFTasBUGuhrMCGXi7TOXIeOfLLinH2LypGwTvH4p+OgXFOUiflJCo2k6mh0/Bv4vEu6D6Q1slw9AKnFbnByoT6hPUTfOjyu2D1z3wpQqLE5ErPU9vvgRNbR9gRcPSw6aU1LDhFEi/fde8s0A3sg1yAhCwWXKRAq0Ok2Eyi2eUgz9i1NLJN8oH//Sx5lNfeSVoQJZWHfWNmEqZtjmxHWI3rwdXFzuivSfbJGh4S8LBgrj7k8Fc8beDRXOdAmHmCnbJYi9X8WpHIEJMAotaFPZbf1xLR987Fi05SpcINalHN60H6NMFmrGcTHqLN2rQIk4jQToyGowg4pxx3nmZD+ZyC6NDdAlAAA1HcRZggGjAPrXq6Zqtf4ue7ryWeJjGtvbPRBkuGt49HDuJi8yJtN0msiJqa/EeyccusqtVxz3NQ7dRm6V/vYs8rWh7P7LyuPuQ0FSAnyVuTidSSjzdAfURny+OjTaWScM3gkivw5I8t+2PZOP+D2WWlJMHIFeojnlVXjv3K+nVdHUdoEodYRzWa8kggYX9MJLYF3M52cIeK/TELij8uCW4bEdQ0GHJ9Q+Rg1SIhA6BnMsM+PnIzp4jpG0GKmNAKoKb747b1tthOrXwSeVTPBCNLi74V3tT7nc=
  app: bali-compiler-server
  on:
    branch: master
